#!/bin/bash
# postBuild

# 进入用户主目录（绝对路径）
cd /home/jovyan

# 下载并解压 SUMO
wget https://sumo.dlr.de/releases/1.18.0/sumo-1.18.0-Linux64.tar.gz
tar -xzf sumo-1.18.0-Linux64.tar.gz

# 设置全局环境变量（所有用户生效）
echo "export SUMO_HOME=/home/jovyan/sumo-1.18.0" | sudo tee /etc/profile.d/sumo.sh
echo "export PATH=\$PATH:/home/jovyan/sumo-1.18.0/bin" | sudo tee -a /etc/profile.d/sumo.sh

# 立即生效
source /etc/profile.d/sumo.sh
