#!/bin/bash
# postBuild

# 下载并编译安装 SUMO 1.18.0
wget https://sumo.dlr.de/releases/1.18.0/sumo-src-1.18.0.tar.gz
tar -xzf sumo-src-1.18.0.tar.gz
cd sumo-1.18.0
mkdir build && cd build
cmake ..
make -j$(nproc)
make install

# 设置环境变量
echo "export SUMO_HOME=/usr/local/share/sumo" >> ~/.bashrc
echo "export PATH=\$PATH:/usr/local/bin" >> ~/.bashrc
source ~/.bashrc
